/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as WarrantyImport } from './routes/warranty'
import { Route as MagazinesImport } from './routes/magazines'
import { Route as DetectionImport } from './routes/detection'
import { Route as DataCampImport } from './routes/data-camp'
import { Route as CarsImport } from './routes/cars'
import { Route as IndexImport } from './routes/index'
import { Route as MagazineIdImport } from './routes/magazine.$id'

// Create/Update Routes

const WarrantyRoute = WarrantyImport.update({
  path: '/warranty',
  getParentRoute: () => rootRoute,
} as any)

const MagazinesRoute = MagazinesImport.update({
  path: '/magazines',
  getParentRoute: () => rootRoute,
} as any)

const DetectionRoute = DetectionImport.update({
  path: '/detection',
  getParentRoute: () => rootRoute,
} as any)

const DataCampRoute = DataCampImport.update({
  path: '/data-camp',
  getParentRoute: () => rootRoute,
} as any)

const CarsRoute = CarsImport.update({
  path: '/cars',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const MagazineIdRoute = MagazineIdImport.update({
  path: '/magazine/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/cars': {
      id: '/cars'
      path: '/cars'
      fullPath: '/cars'
      preLoaderRoute: typeof CarsImport
      parentRoute: typeof rootRoute
    }
    '/data-camp': {
      id: '/data-camp'
      path: '/data-camp'
      fullPath: '/data-camp'
      preLoaderRoute: typeof DataCampImport
      parentRoute: typeof rootRoute
    }
    '/detection': {
      id: '/detection'
      path: '/detection'
      fullPath: '/detection'
      preLoaderRoute: typeof DetectionImport
      parentRoute: typeof rootRoute
    }
    '/magazines': {
      id: '/magazines'
      path: '/magazines'
      fullPath: '/magazines'
      preLoaderRoute: typeof MagazinesImport
      parentRoute: typeof rootRoute
    }
    '/warranty': {
      id: '/warranty'
      path: '/warranty'
      fullPath: '/warranty'
      preLoaderRoute: typeof WarrantyImport
      parentRoute: typeof rootRoute
    }
    '/magazine/$id': {
      id: '/magazine/$id'
      path: '/magazine/$id'
      fullPath: '/magazine/$id'
      preLoaderRoute: typeof MagazineIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cars': typeof CarsRoute
  '/data-camp': typeof DataCampRoute
  '/detection': typeof DetectionRoute
  '/magazines': typeof MagazinesRoute
  '/warranty': typeof WarrantyRoute
  '/magazine/$id': typeof MagazineIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cars': typeof CarsRoute
  '/data-camp': typeof DataCampRoute
  '/detection': typeof DetectionRoute
  '/magazines': typeof MagazinesRoute
  '/warranty': typeof WarrantyRoute
  '/magazine/$id': typeof MagazineIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/cars': typeof CarsRoute
  '/data-camp': typeof DataCampRoute
  '/detection': typeof DetectionRoute
  '/magazines': typeof MagazinesRoute
  '/warranty': typeof WarrantyRoute
  '/magazine/$id': typeof MagazineIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cars'
    | '/data-camp'
    | '/detection'
    | '/magazines'
    | '/warranty'
    | '/magazine/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cars'
    | '/data-camp'
    | '/detection'
    | '/magazines'
    | '/warranty'
    | '/magazine/$id'
  id:
    | '__root__'
    | '/'
    | '/cars'
    | '/data-camp'
    | '/detection'
    | '/magazines'
    | '/warranty'
    | '/magazine/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CarsRoute: typeof CarsRoute
  DataCampRoute: typeof DataCampRoute
  DetectionRoute: typeof DetectionRoute
  MagazinesRoute: typeof MagazinesRoute
  WarrantyRoute: typeof WarrantyRoute
  MagazineIdRoute: typeof MagazineIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CarsRoute: CarsRoute,
  DataCampRoute: DataCampRoute,
  DetectionRoute: DetectionRoute,
  MagazinesRoute: MagazinesRoute,
  WarrantyRoute: WarrantyRoute,
  MagazineIdRoute: MagazineIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/cars",
        "/data-camp",
        "/detection",
        "/magazines",
        "/warranty",
        "/magazine/$id"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/cars": {
      "filePath": "cars.tsx"
    },
    "/data-camp": {
      "filePath": "data-camp.tsx"
    },
    "/detection": {
      "filePath": "detection.tsx"
    },
    "/magazines": {
      "filePath": "magazines.tsx"
    },
    "/warranty": {
      "filePath": "warranty.tsx"
    },
    "/magazine/$id": {
      "filePath": "magazine.$id.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
