/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as MagazinesRouteImport } from './routes/magazines'
import { Route as EtsRouteImport } from './routes/ets'
import { Route as DataCampRouteImport } from './routes/data-camp'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MagazineIdRouteImport } from './routes/magazine.$id'

const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const MagazinesRoute = MagazinesRouteImport.update({
  id: '/magazines',
  path: '/magazines',
  getParentRoute: () => rootRouteImport,
} as any)
const EtsRoute = EtsRouteImport.update({
  id: '/ets',
  path: '/ets',
  getParentRoute: () => rootRouteImport,
} as any)
const DataCampRoute = DataCampRouteImport.update({
  id: '/data-camp',
  path: '/data-camp',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MagazineIdRoute = MagazineIdRouteImport.update({
  id: '/magazine/$id',
  path: '/magazine/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/data-camp': typeof DataCampRoute
  '/ets': typeof EtsRoute
  '/magazines': typeof MagazinesRoute
  '/partners': typeof PartnersRoute
  '/magazine/$id': typeof MagazineIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/data-camp': typeof DataCampRoute
  '/ets': typeof EtsRoute
  '/magazines': typeof MagazinesRoute
  '/partners': typeof PartnersRoute
  '/magazine/$id': typeof MagazineIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/data-camp': typeof DataCampRoute
  '/ets': typeof EtsRoute
  '/magazines': typeof MagazinesRoute
  '/partners': typeof PartnersRoute
  '/magazine/$id': typeof MagazineIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/data-camp'
    | '/ets'
    | '/magazines'
    | '/partners'
    | '/magazine/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/data-camp' | '/ets' | '/magazines' | '/partners' | '/magazine/$id'
  id:
    | '__root__'
    | '/'
    | '/data-camp'
    | '/ets'
    | '/magazines'
    | '/partners'
    | '/magazine/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DataCampRoute: typeof DataCampRoute
  EtsRoute: typeof EtsRoute
  MagazinesRoute: typeof MagazinesRoute
  PartnersRoute: typeof PartnersRoute
  MagazineIdRoute: typeof MagazineIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/magazines': {
      id: '/magazines'
      path: '/magazines'
      fullPath: '/magazines'
      preLoaderRoute: typeof MagazinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ets': {
      id: '/ets'
      path: '/ets'
      fullPath: '/ets'
      preLoaderRoute: typeof EtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-camp': {
      id: '/data-camp'
      path: '/data-camp'
      fullPath: '/data-camp'
      preLoaderRoute: typeof DataCampRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/magazine/$id': {
      id: '/magazine/$id'
      path: '/magazine/$id'
      fullPath: '/magazine/$id'
      preLoaderRoute: typeof MagazineIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DataCampRoute: DataCampRoute,
  EtsRoute: EtsRoute,
  MagazinesRoute: MagazinesRoute,
  PartnersRoute: PartnersRoute,
  MagazineIdRoute: MagazineIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
